trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  # Setup Node.js
  - task: NodeTool@0
    inputs:
      versionSpec: '18.x'

  # Build frontend
  - script: |
      cd frontend
      npm install
      npm run build
    displayName: "Build React frontend"

  # Build + test backend
  - script: |
      cd backend
      npm install
      npm run build || echo "No build step for backend"
    displayName: "Prepare backend"

  # Publish artifacts
  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: 'frontend/build'
      artifactName: 'frontend-dist'

  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: 'backend'
      artifactName: 'backend-dist'
